name: Format Check

on:
  pull_request:
    branches: [ main ]

jobs:
  format:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: npm install
      
      - name: Check formatting
        run: |
          npm run format
          # Check if any files changed
          if [ -n "$(git status --porcelain)" ]; then
            echo "❌ Code is not formatted. Please run 'npm run format' locally"
            exit 1
          else
            echo "✅ Code is properly formatted"
          fi