name: Test CLI

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install and build
        run: |
          npm install
          npm run build
      
      - name: Test nestify new command
        run: |
          node dist/index.js new test-app --skip-git --skip-install
          # Check if the app was created
          ls -la test-app